// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousCommand.h"
#include "AutoSonar.h"
#include "AutoGearPlacement.h"
#include "IntrptGGCmd.h"
#include "AutoForward.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutonomousCommand::AutonomousCommand(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutonomousCommand::Initialize() {
	Robot::gearPneumatics->SetSolen(false);
	//Robot::driveBase->setCoastBreak(false);
}

// Called repeatedly when this Command is scheduled to run
void AutonomousCommand::Execute() {

	if (SmartDashboard::GetBoolean("DB/Button 0", false)) {
		SmartDashboard::PutString("DB/String 0", "Starting Left Gear");
		cmd.reset(new AutoGearPlacement(0));
		cmd->Start();
	} else if (SmartDashboard::GetBoolean("DB/Button 1", false)) {
		SmartDashboard::PutString("DB/String 0", "Starting Mid Gear");
		cmd.reset(new AutoGearPlacement(1));
		cmd->Start();
	}  else if (SmartDashboard::GetBoolean("DB/Button 2", false)) {
		SmartDashboard::PutString("DB/String 0", "Starting Right Gear");
		cmd.reset(new AutoGearPlacement(2));
		cmd->Start();
	} else {
		SmartDashboard::PutString("DB/String 0", "Doing Nothing");
	}

}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousCommand::IsFinished() {
    return true;
}

// Called once after isFinished returns true
void AutonomousCommand::End() {
	//sets motors to coast
	//Robot::driveBase->setCoastBreak(true);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousCommand::Interrupted() {
	cmd.reset(new IntrptGGCmd());
	cmd->Start();
	Robot::driveBase->BetterDriveMethod(0,0);

}
