// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutoForward.h"
#include "Commands/AutoGearPlacement.h"
#include "Commands/AutoSonar.h"
#include "Commands/AutoTurn.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Center.h"
#include "Commands/GearRelease.h"
#include "Commands/GearVision.h"
#include "Commands/Move.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    gamePad.reset(new Joystick(2));
    
    rightJoystick.reset(new Joystick(1));
    
    leftJoystick.reset(new Joystick(0));
    
    gearBtn.reset(new JoystickButton(leftJoystick.get(), 2));
    gearBtn->WhenPressed(new GearRelease());

    // SmartDashboard Buttons
    SmartDashboard::PutData("AutoSonar", new AutoSonar());
    SmartDashboard::PutData("Center", new Center());
    SmartDashboard::PutData("GearVision", new GearVision());
    SmartDashboard::PutData("AutoGearPlacement", new AutoGearPlacement(false));
    SmartDashboard::PutData("AutoTurn", new AutoTurn(0,0));
    SmartDashboard::PutData("AutoForward", new AutoForward(0,0));
    SmartDashboard::PutData("GearRelease", new GearRelease());
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getLeftJoystick() {
   return leftJoystick;
}

std::shared_ptr<Joystick> OI::getRightJoystick() {
   return rightJoystick;
}

std::shared_ptr<Joystick> OI::getGamePad() {
   return gamePad;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
